#!/usr/bin/env node

// Splitting
console.log("ant bat cat".split(" "));
let a = "A man, a plan, a canal, Panama".split(", ");
console.log(a.reverse());

// Slicing
let b = [42, 18, 20, 8];
console.log(b.slice(1)); // start from index 1
console.log(b.slice(1, 3));
console.log(b.slice(-1)[0]); //nice way to get last element
let c = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
console.log(c.slice(2, c.length - 3));


