#!/usr/local/bin/node
// comments are done with backslashes
/* or use this
hahhaha
*/

console.log("hello, world!"); // printing

// vars in ES6
let firstName = "Mike";
let swag = "Andrew";

// var still works
var niarg = "cool";

// interpolation of strings
let full = `${swag} is ${niarg}`;
console.log(full);

console.log(niarg, swag); //auto inserts a space between the 2